// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	redis "github.com/gomodule/redigo/redis"
	mock "github.com/stretchr/testify/mock"
)

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

// Connection provides a mock function with given fields:
func (_m *RedisClient) Connection() redis.Conn {
	ret := _m.Called()

	var r0 redis.Conn
	if rf, ok := ret.Get(0).(func() redis.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.Conn)
		}
	}

	return r0
}
